import Anthropic from '@anthropic-ai/sdk';
import { supabase } from '../../lib/supabase';

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end();

  const { key, messages } = req.body;
  if (!key || !messages || messages.length === 0) {
    return res.status(400).json({ error: 'Missing key or messages.' });
  }

  // Validate embed key
  const isInternal = key === process.env.INTERNAL_EMBED_KEY;
  if (!isInternal) {
    const { data: embedKey } = await supabase
      .from('embed_keys')
      .select('id')
      .eq('key', key)
      .eq('is_active', true)
      .single();
    if (!embedKey) return res.status(401).json({ error: 'Invalid key.' });
  }

  const transcript = messages
    .map(m => (m.role === 'user' ? 'Student: ' : 'Linkist: ') + m.content)
    .join('\n\n');

  const response = await anthropic.messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 1024,
    messages: [
      {
        role: 'user',
        content: `You are summarizing a conversation between a student and Linkist, an AI assistant that helps youth find volunteer opportunities, internships, and scholarships. This summary is for a college coach or advisor who wants to understand the student's interests and what opportunities were recommended.

Write a brief, structured report with these sections:
1. **About the Student** — What did they share about themselves? (age, city, interests, goals, background — only what was mentioned)
2. **Opportunities Discussed** — List the specific opportunities or types of opportunities Linkist recommended, with URLs if mentioned
3. **Key Takeaways** — 2-3 sentences summarizing what stood out about this student's interests and the best next steps for them

Keep it concise and professional. Do not invent details not present in the conversation.

Return ONLY a JSON object:
{
  "studentSummary": "...",
  "opportunities": ["...", "..."],
  "takeaways": "..."
}

Conversation:
${transcript}`,
      },
    ],
  });

  const raw = response.content[0].type === 'text' ? response.content[0].text : '';
  let parsed;
  try {
    const json = raw.replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/, '').trim();
    parsed = JSON.parse(json);
  } catch {
    parsed = { studentSummary: 'Could not parse summary.', opportunities: [], takeaways: raw.slice(0, 500) };
  }

  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const opportunitiesHtml = parsed.opportunities && parsed.opportunities.length > 0
    ? '<ul>' + parsed.opportunities.map(function (o) {
        // Auto-link URLs in opportunity text
        var linked = o.replace(/(https?:\/\/[^\s]+)/g, '<a href="$1" style="color:#ed1869;">$1</a>');
        return '<li>' + linked + '</li>';
      }).join('') + '</ul>'
    : '<p style="color:#888;">No specific listings mentioned.</p>';

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Linkist Conversation Report</title>
<style>
  body { font-family: Georgia, serif; max-width: 680px; margin: 40px auto; padding: 0 24px; color: #1a1a1a; line-height: 1.7; }
  .header { border-bottom: 2px solid #ed1869; padding-bottom: 16px; margin-bottom: 32px; }
  .logo { font-family: Arial, sans-serif; font-weight: 900; font-size: 22px; color: #ed1869; letter-spacing: -0.5px; }
  .date { font-size: 13px; color: #888; margin-top: 4px; }
  h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 0.08em; color: #ed1869; margin: 28px 0 8px; }
  p, li { font-size: 15px; }
  ul { padding-left: 20px; margin: 0; }
  li { margin-bottom: 6px; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #eee; font-size: 12px; color: #aaa; }
  @media print {
    body { margin: 20px auto; }
    a { color: #ed1869 !important; }
  }
</style>
</head>
<body>
  <div class="header">
    <div class="logo">Linkist</div>
    <div class="date">Conversation Report &mdash; ${date}</div>
  </div>

  <h2>About the Student</h2>
  <p>${parsed.studentSummary || 'No personal details shared.'}</p>

  <h2>Opportunities Discussed</h2>
  ${opportunitiesHtml}

  <h2>Key Takeaways</h2>
  <p>${parsed.takeaways || ''}</p>

  <div class="footer">Generated by Linkist &mdash; <a href="https://changeist.org" style="color:#aaa;">changeist.org</a></div>
</body>
</html>`;

  return res.status(200).json({ html });
}
